version: '3.4'

services:
  menuplan:
    image: menuplanimg2:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "MenuPlan"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_menuplan$
    volumes:
      - C:\Users\Maxi\.FH\SWE\12FacMicroservice\12FacMs\MenuPlan:/app
      - C:\Users\Maxi\.FH\SWE\12FacMicroservice\12FacMs:/src
      - C:\Users\markus.wagner\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_menuplan$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_menuplan$ \"/app/bin/Debug/netcoreapp3.1/MenuPlan.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true