name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: build code base
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Install dependencies
      run: dotnet restore MenuPlan/MenuPlan.csproj
    - name: Build
      run: dotnet build MenuPlan/MenuPlan.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test MenuPlan/MenuPlan.csproj --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish MenuPlan/MenuPlan.csproj -c Release  
    - name: Archive production artefakt
      uses: actions/upload-artifact@v2
      with:
        name: Production menums dotnetcore
        path: |            
          MenuPlan/bin/Release/netcoreapp3.1/publish/**
    - uses: actions/checkout@v2
    - name: Build  Docker image
      run: docker build . --file MenuPlan/Dockerfile --t leageorg/swe2020wm:abgabe
    - name: Login to Docker Hub
      run: docker login --username=leageorg --password=guljajew
    - name: show images 
      run: docker images
    - name: push to dockerhub
      run: docker push leageorg/swe2020wm:tagname 
#      uses: docker/build-push-action@v1
#      with:
#        username: leageorg
#        password: guljajew
#        repository: leageorg/swe2020wm
#        tag_with_ref: true
